version: "3.9"

services:
  api:
    image: livemap-api
    build:
      context: .
      dockerfile: LiveMap.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CON=Server=sql;Initial Catalog=LiveMap;User Id=sa;Password=SomeStrongPw2201755#!;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - sql

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SomeStrongPw2201755#!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"