version: "3.9"

services:
  api:
    image: livemap-api
    build:
      context: .
      dockerfile: LiveMap.Api/Dockerfile
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CON=Server=sql;Initial Catalog=LiveMap;User Id=sa;Password=SomeStrongPw2201755#!;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - sql

  web:
    image: livemap-web
    build:
      context: .
      dockerfile: LiveMapDashboard.Web/Dockerfile
    ports:
      - "5115:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL=http://api:8080
      - IMAGESERVER_URL=http://imageserver:8080
    depends_on:
      - api
   
  imageserver:
    image: livemap-imageserver
    build:
      context: .
      dockerfile: LiveMap.ImageServer/Dockerfile
    ports:
      - "5007:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SomeStrongPw2201755#!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"    